### ISSUE TITLE
运行make run时报错

### ISSUE THREAD

**Issue by Mr-Phoebe** [LastAvenger/OS67#11]
我安装的Bochs是2012年的2.6
创建文件系统的时候

我把`bximage bin/rootfs.img -hd=10M -imgmode=flat -mode=create -q`改为了`bximage bin/rootfs.img -hd -size=10M  -mode="flat" -q`，不然也是无法运行`make fs`，报错是说bximage不识别-hd10M的指令。

改完就可以编译内核了。但是不能运行Bochs，导致make run错误

```
bx_dbg_read_linear: physical memory read error (phy=0x0000000000000000, lin=0x0000000000000000)
00000000000i[CTRL ] quit_sim called with exit code 1
```

想问问，是什么原因造成的。是不是因为包升级导致接口改变什么的。

**Comment by SilverRainZ** [comment]
Hello，bochs 2.6.5 并不是最新版，最新版是 2.6.9。

我看了一下，`bximage` 在 13 年的这个 [commit](https://github.com/svn2github/bochs/commit/60e7e1a662b6675e67a04adfff136821cd1fea7e#diff-3cbf83d4d12837cb8f7c98fe065c5e18) 里用 C++ 重写了并且 `-szie` 参数也被废弃了，但是新的 bximage 没有被打包到项目的 binary 里去 。在 14 年 7 月的这个 [commit](https://github.com/svn2github/bochs/commit/d3babd7a7efaab9c27ccb6eb47b454758a12d3eb#diff-79e20d3015220f4da37c33721711bdcdL47) 里正式把新的 bximage 打包进了项目，所以你应该至少用 14 年 7 月之后的 release，比如 2.6.7。

**Comment by Mr-Phoebe** [comment]
恩，我现在就在安装bochs 2.6.9。但是我不太理解你说的项目的binary指的是哪个项目，是你写的OS还是bochs。
另外，如果升级了依赖，其他命令，比如，Makefile脚本，bachsrc.bxrc的配置有什么需要改的地方么？

**Comment by SilverRainZ** [comment]
是 bochs，我刚刚试运行了一下，应该没有需要改的地方。

**Comment by Mr-Phoebe** [comment]
已解决
附上bochs的安装教程
http://www.itread01.com/articles/1488937138.html

感谢
