### ISSUE TITLE
boot代码问题

### ISSUE THREAD

**Issue by wjk13720041** [LastAvenger/OS67#14]
bootsect.asm 文件  retry 下的最后一条语句应该跳回retry重新读取，而不是继续读下一块的数据

**Comment by SilverRainZ** [comment]
看了一下，确实是这样的，您愿意帮忙修复这个问题么？

**Comment by wjk13720041** [comment]
如果可以的话我当然愿意，需要我怎么做

**Comment by SilverRainZ** [comment]
修正后提交一个 Pull Request?

**Comment by wjk13720041** [comment]
好的

**Comment by wjk13720041** [comment]
改好了，我用开源社区比较少，不知道是不是帮助到了你

**Comment by andysim3d** [comment]
@SilverRainZ  #15 created PR for @wjk13720041
