### ISSUE TITLE
关于dev/con.c和inc/con.h的问题

### ISSUE THREAD

**Issue by OrlogLee** [LastAvenger/OS67#3]
在Windows下clone这个repo，会出现不能创建名叫con的文件的问题。

error: unable to create file dev/con.c (No such file or directory)
error: unable to create file inc/con.h (No such file or directory)

建议修改这两个文件的名字。

**Comment by SilverRainZ** [comment]
确实是这样诶…… con 是个设备名来的。
抱歉给你造成困扰了，我来改一下。

~~不过没有在 Windows 下编译过，还是建议 Linux 吧~~

**Comment by SilverRainZ** [comment]
要成功 `make fs` 的话，你还需要解决 `mount` `bximage` `mkfs` 这些命令的问题，不知道在 windows 上有没有对应的软件。

**Comment by OrlogLee** [comment]
我只在Windows下clone ，并不编译。
