### ISSUE TITLE
cat has a wrong name

### ISSUE THREAD

**Issue by Artoria2e5** [LastAvenger/OS67#7]
The name _cat_ is for concatenate, just like the word _concat_ in other languages. Let's call the current cat `kitten` for it only reads a file.

**Comment by SilverRainZ** [comment]
23333.

然而 cat 不止是读文件啊，试试 `ls | cat`.
~~虽然可能有 bug 就是了~~

**Comment by Artoria2e5** [comment]
Let me reword. For it only reads a file or nothing （
